import type { User, Client, Lead } from '../types';

/* ── Users ── */

export const USERS: User[] = [
  {
    id: 'u1',
    name: 'Александр Морозов',
    firstName: 'Александр',
    lastName: 'Морозов',
    email: 'admin@salespilot.ru',
    role: 'admin',
    avatar: 'АМ',
  },
  {
    id: 'u2',
    name: 'Анна Кузнецова',
    firstName: 'Анна',
    lastName: 'Кузнецова',
    email: 'anna@salespilot.ru',
    role: 'manager',
    avatar: 'АК',
  },
  {
    id: 'u3',
    name: 'Иван Соколов',
    firstName: 'Иван',
    lastName: 'Соколов',
    email: 'ivan@salespilot.ru',
    role: 'manager',
    avatar: 'ИС',
  },
];

export const CREDENTIALS: Record<string, { password: string; userId: string }> = {
  'admin@salespilot.ru': { password: 'admin', userId: 'u1' },
  'anna@salespilot.ru': { password: 'manager', userId: 'u2' },
  'ivan@salespilot.ru': { password: 'manager', userId: 'u3' },
};

/** Built-in demo users that must never be deleted or have their email changed. */
export const SEED_USER_IDS: readonly string[] = USERS.map((u) => u.id);

/* ── Clients ── */

export const CLIENTS: Client[] = [
  {
    id: 'c1',
    name: 'Ольга Никитина',
    email: 'olga@technosfera.ru',
    phone: '+7 (921) 234-89-01',
    company: 'ООО «ТехноСфера»',
    status: 'active',
    managerId: 'u2',
    managerName: 'Анна Кузнецова',
    createdAt: '2025-06-12',
    lastActivity: '2026-04-03',
    revenue: 4200000,
    notes: 'Корпоративный тариф. Квартальная встреча запланирована на апрель.',
    convertedFromLead: true,
  },
  {
    id: 'c2',
    name: 'Егор Васильев',
    email: 'egor@nevasoft.ru',
    phone: '+7 (911) 345-67-12',
    company: '«Нева Софт»',
    status: 'active',
    managerId: 'u2',
    managerName: 'Анна Кузнецова',
    createdAt: '2025-03-21',
    lastActivity: '2026-04-06',
    revenue: 6350000,
    notes: 'Ключевой клиент. Прорабатывают интеграцию по API со своей CRM.',
  },
  {
    id: 'c3',
    name: 'София Орлова',
    email: 'sofia@ladoga-market.ru',
    phone: '+7 (931) 456-23-90',
    company: '«Ладога Маркет»',
    status: 'prospect',
    managerId: 'u3',
    managerName: 'Иван Соколов',
    createdAt: '2026-01-09',
    lastActivity: '2026-03-28',
    revenue: 0,
    notes: 'Были на вебинаре в январе. Интересует тариф «Рост».',
  },
  {
    id: 'c4',
    name: 'Даниил Кузьмин',
    email: 'daniil@volgalogistik.ru',
    phone: '+7 (846) 567-34-01',
    company: '«Волга Логистик»',
    status: 'inactive',
    managerId: 'u3',
    managerName: 'Иван Соколов',
    createdAt: '2024-11-15',
    lastActivity: '2025-09-20',
    revenue: 1590000,
    notes: 'Приостановили подписку. Вернуться к разговору во II квартале 2026.',
  },
  {
    id: 'c5',
    name: 'Мария Лебедева',
    email: 'maria@severcrm.ru',
    phone: '+7 (902) 123-45-67',
    company: '«Север CRM»',
    status: 'active',
    managerId: 'u2',
    managerName: 'Анна Кузнецова',
    createdAt: '2025-08-02',
    lastActivity: '2026-04-05',
    revenue: 3360000,
    notes: 'Выход на рынок СЗФО. Нужна расширенная поддержка.',
    convertedFromLead: true,
  },
  {
    id: 'c6',
    name: 'Артём Поляков',
    email: 'artem@baltikdigital.ru',
    phone: '+7 (812) 765-43-21',
    company: '«Балтик Диджитал»',
    status: 'churned',
    managerId: 'u3',
    managerName: 'Иван Соколов',
    createdAt: '2024-07-19',
    lastActivity: '2025-06-11',
    revenue: 790000,
    notes: 'Ушли к конкуренту. Основной фактор — чувствительность к цене.',
  },
  {
    id: 'c7',
    name: 'Алиса Громова',
    email: 'alisa@avroramedia.ru',
    phone: '+7 (495) 678-90-12',
    company: '«Аврора Медиа»',
    status: 'active',
    managerId: 'u2',
    managerName: 'Анна Кузнецова',
    createdAt: '2025-11-30',
    lastActivity: '2026-04-01',
    revenue: 2140000,
    notes: 'Сезонный бизнес, пик в IV квартале. Есть потенциал на аналитику.',
  },
  {
    id: 'c8',
    name: 'Никита Фёдоров',
    email: 'nikita@uralmash-systems.ru',
    phone: '+7 (343) 234-56-78',
    company: 'ООО «Уралмаш Системс»',
    status: 'prospect',
    managerId: 'u3',
    managerName: 'Иван Соколов',
    createdAt: '2026-02-18',
    lastActivity: '2026-03-22',
    revenue: 0,
    notes: 'Рекомендация от «Север CRM». Назначена демонстрация.',
  },
  {
    id: 'c9',
    name: 'Виктория Зайцева',
    email: 'victoria@grandcapital.ru',
    phone: '+7 (499) 890-12-34',
    company: '«Гранд Капитал»',
    status: 'active',
    managerId: 'u3',
    managerName: 'Иван Соколов',
    createdAt: '2025-05-07',
    lastActivity: '2026-04-04',
    revenue: 4660000,
    notes: 'Технический заказчик. Нужна детальная документация по безопасности.',
    convertedFromLead: true,
  },
  {
    id: 'c10',
    name: 'Павел Беляев',
    email: 'pavel@sibirtelecom.ru',
    phone: '+7 (383) 012-34-56',
    company: '«Сибирь Телеком»',
    status: 'inactive',
    managerId: 'u2',
    managerName: 'Анна Кузнецова',
    createdAt: '2025-01-23',
    lastActivity: '2025-11-14',
    revenue: 420000,
    notes: 'Небольшой аккаунт. Ограниченный бюджет. Вернуться в середине 2026.',
  },
];

/* ── Leads ── */

export const LEADS: Lead[] = [
  {
    id: 'l1',
    name: 'Галина Киреева',
    email: 'galina@yasnofinans.ru',
    phone: '+7 (903) 111-22-33',
    company: '«ЯсноФинанс»',
    status: 'new',
    source: 'Website',
    value: 1250000,
    managerId: 'u2',
    managerName: 'Анна Кузнецова',
    createdAt: '2026-04-01',
    notes: 'Скачали white paper по прогнозированию продаж.',
  },
  {
    id: 'l2',
    name: 'Роман Мельников',
    email: 'roman@mostech.ru',
    phone: '+7 (495) 998-76-54',
    company: '«МосТех»',
    status: 'contacted',
    source: 'LinkedIn',
    value: 2400000,
    managerId: 'u3',
    managerName: 'Иван Соколов',
    createdAt: '2026-03-18',
    notes: 'Ответили на письмо. Хотят демонстрацию продукта.',
  },
  {
    id: 'l3',
    name: 'Ксения Мартынова',
    email: 'ksenia@pitersoft.ru',
    phone: '+7 (812) 123-45-67',
    company: '«ПитерСофт»',
    status: 'qualified',
    source: 'Referral',
    value: 3600000,
    managerId: 'u2',
    managerName: 'Анна Кузнецова',
    createdAt: '2026-02-25',
    notes: 'Рекомендация от «Нева Софт». Хорошо подходит корпоративный тариф.',
  },
  {
    id: 'l4',
    name: 'Олег Рашидов',
    email: 'oleg@kavkazstroy.ru',
    phone: '+7 (928) 123-45-67',
    company: '«Кавказ Строй»',
    status: 'proposal',
    source: 'Trade Show',
    value: 4750000,
    managerId: 'u3',
    managerName: 'Иван Соколов',
    createdAt: '2026-01-14',
    notes: 'Познакомились на отраслевой выставке. КП отправлено 15 марта.',
  },
  {
    id: 'l5',
    name: 'Анна Лазарева',
    email: 'anna@zelenayaliniya.ru',
    phone: '+7 (383) 333-44-55',
    company: '«Зелёная Линия»',
    status: 'proposal',
    source: 'Website',
    value: 1900000,
    managerId: 'u2',
    managerName: 'Анна Кузнецова',
    createdAt: '2025-12-08',
    notes: 'Близки к сделке. Обсуждают годовой контракт.',
  },
  {
    id: 'l6',
    name: 'Виктор Сорокин',
    email: 'viktor@polyarniy.ru',
    phone: '+7 (8152) 12-34-56',
    company: '«Полярный»',
    status: 'lost',
    source: 'Cold Call',
    value: 3000000,
    managerId: 'u3',
    managerName: 'Иван Соколов',
    createdAt: '2025-11-20',
    notes: 'Проиграли конкуренту. Бюджет распределили в другую сторону.',
  },
  {
    id: 'l7',
    name: 'Аиша Юсупова',
    email: 'aisha@novamed.ru',
    phone: '+7 (843) 555-66-77',
    company: '«Нова Мед»',
    status: 'new',
    source: 'Webinar',
    value: 1650000,
    managerId: 'u2',
    managerName: 'Анна Кузнецова',
    createdAt: '2026-04-05',
    notes: 'Были на апрельском вебинаре по управлению воронкой.',
  },
];
